### ISSUE TITLE
Add information about recursing submodules for markup2 to the readme

### ISSUE THREAD

**Issue by randomouscrap98** [ilovecherries/glimmer#2]
Literally just the title, make sure people know to pull the submodules

**Comment by randomouscrap98** [comment]
In case I forget, the command for downloading them after the fact is:

`git submodule update --init --recursive`

and to download them on clone:

`git clone --recursive`

**Comment by ilovecherries** [comment]
There is no longer a need to add this to the documentation since it is now included as a package.
